-- DATA VIEWING PURPOSES
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPT2;
SELECT * FROM POSITIONS;
SELECT * FROM ALLOWANCE;
SELECT * FROM POS_ALL;
SELECT * FROM PROJ;
SELECT * FROM GRADE;
SELECT * FROM EMP_PHONE;
SELECT * FROM LOGIN;
SELECT * FROM TRANSACTIONS;
SELECT * FROM VEHICLE;
SELECT * FROM OVERTIME;

-- INITIALIZATION
DROP TABLE OVERTIME;
DROP TABLE VEHICLE;
DROP TABLE TRANSACTIONS;
DROP TABLE ASSIGNED_TO;
DROP TABLE LOGIN;
DROP TABLE EMP_PHONE;
DROP TABLE GRADE;
DROP TABLE PROJ;
DROP TABLE EMPLOYEE;
DROP TABLE DEPT2;
DROP TABLE POS_ALL;
DROP TABLE ALLOWANCE;
DROP TABLE POSITIONS;

-- TABLE CREATION
CREATE TABLE DEPT2 
(DNAME VARCHAR2(15), DESC_ VARCHAR2(25) NOT NULL,
CONSTRAINT DEPT_DNAME PRIMARY KEY (DNAME));

CREATE TABLE GRADE 
(GRADE_TYPE VARCHAR2(1), MINSAL NUMBER (5), MAXSAL NUMBER(5), HOURLY_PAY NUMBER(4),
CONSTRAINT GRADE_GRADE_TYPE PRIMARY KEY (GRADE_TYPE));

CREATE TABLE ALLOWANCE
(ALLOWANCE_TYPE VARCHAR2(15), AM0UNT NUMBER(5) NOT NULL,
CONSTRAINT ALL_ATYPE PRIMARY KEY (ALLOWANCE_TYPE));

CREATE TABLE POSITIONS
(POSITION_TYPE VARCHAR2(10), CONSTRAINT POS_PTYPE PRIMARY KEY (POSITION_TYPE));

CREATE TABLE POS_ALL
(POSITION_TYPE VARCHAR2(10), ALLOWANCE_TYPE VARCHAR2(15),
CONSTRAINT PA_PRIM PRIMARY KEY (POSITION_TYPE, ALLOWANCE_TYPE), CONSTRAINT A_FK FOREIGN KEY (ALLOWANCE_TYPE) REFERENCES ALLOWANCE(ALLOWANCE_TYPE),
CONSTRAINT P_FK FOREIGN KEY (POSITION_TYPE) REFERENCES POSITIONS(POSITION_TYPE));

CREATE TABLE EMPLOYEE
(EMP_ID NUMBER(3),ENAME VARCHAR2(40) NOT NULL, POSITION_TYPE VARCHAR2(10), GENDER VARCHAR2(1), SALARY NUMBER(5), DOB DATE NOT NULL, HIREDATE DATE NOT NULL, COMM NUMBER(5), DNAME VARCHAR2(15), USERNAME VARCHAR2(20) NOT NULL,
CONSTRAINT EMPLOYEE_EMP_ID PRIMARY KEY (EMP_ID), CONSTRAINT EMPLOYEE_GENDER_CK CHECK (GENDER = 'M' OR GENDER = 'F'), 
CONSTRAINT EMPLOYEE_DNAME FOREIGN KEY (DNAME) REFERENCES DEPT2(DNAME), CONSTRAINT EMPLOYEE_PTYPE FOREIGN KEY (POSITION_TYPE) REFERENCES POSITIONS(POSITION_TYPE));

CREATE TABLE PROJ
(PROJ_ID NUMBER(3), PNAME VARCHAR2(15) NOT NULL, PDESC VARCHAR2(200),
CONSTRAINT PROJ_PROJECT_ID PRIMARY KEY (PROJ_ID));

CREATE TABLE ASSIGNED_TO
(DNAME VARCHAR2(15) NOT NULL REFERENCES DEPT2(DNAME), PROJ_ID NUMBER(3) NOT NULL REFERENCES PROJ(PROJ_ID), CONSTRAINT ASSIGNED_TO_PRIMARY PRIMARY KEY (DNAME, PROJ_ID));

CREATE TABLE EMP_PHONE
(EMP_ID NUMBER(3), PHONE NUMBER(8) NOT NULL,
CONSTRAINT EP_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID), CONSTRAINT EP_PRIMARY PRIMARY KEY (EMP_ID, PHONE));

CREATE TABLE LOGIN
(USERNAME VARCHAR2(20), USERPASS VARCHAR2(50) NOT NULL, EMP_ID NUMBER(3),
CONSTRAINT LOGIN_PRIMARY PRIMARY KEY (USERNAME), CONSTRAINT LOGIN_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID));

CREATE TABLE TRANSACTIONS 
(TRANSACTION_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP(6), USERNAME VARCHAR2(20) REFERENCES LOGIN(USERNAME), EMP_ID NUMBER(3) REFERENCES EMPLOYEE(EMP_ID), 
POSITION_TYPE VARCHAR2(10) REFERENCES POSITIONS(POSITION_TYPE),
CONSTRAINT T_PRIMARY PRIMARY KEY (TRANSACTION_TIMESTAMP, USERNAME, EMP_ID));

CREATE TABLE VEHICLE (
VEHICLE_ID NUMBER(6), NEXT_M_DATE DATE NOT NULL, V_MODEL VARCHAR2(15) NOT NULL,
MAKE VARCHAR2(15) NOT NULL, EMP_ID NUMBER(3), NOW_DATE DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT MONTHLY_DATE_CK CHECK (NEXT_M_DATE < ADD_MONTHS(NOW_DATE, 3)),
CONSTRAINT V_VEHICLE_ID PRIMARY KEY (VEHICLE_ID),
CONSTRAINT V_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID));

CREATE TABLE OVERTIME 
(OVERTIME_ID NUMBER(3), WORKING_HOURS NUMBER(2), SHIFT VARCHAR2(5), EMP_ID NUMBER(3), OVERTIME_DATE DATE NOT NULL, 
CONSTRAINT O_OVT_ID PRIMARY KEY (OVERTIME_ID), CONSTRAINT O_SHIFT_CK CHECK (SHIFT='DAY' OR SHIFT='NIGHT'),
CONSTRAINT O_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID), CONSTRAINT O_WORKING_HOURS_CK CHECK (WORKING_HOURS <= 8));




--SAMPLE DATA...................................................................
