-- Call the LOGIN_CHECK function
DECLARE
  VALID_LOGIN VARCHAR2(10);
BEGIN
  VALID_LOGIN := LOGIN_CHECK('grub', '789ghi');
  DBMS_OUTPUT.PUT_LINE('Valid login: ' || VALID_LOGIN);

END;

--inserting an employee
INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (290, 'Rii Roxas','HR','F',23000,'04-FEB-2002','19-FEB-2023', NULL,'RESEARCH');
--remove an employee    
DELETE FROM EMPLOYEE WHERE EMP_ID = 290;
SELECT * FROM TRANSACTIONS;

