
--MAX CAPACITY OF DEPARTMENT TRIGGER
CREATE OR REPLACE TRIGGER check_dept_capacity
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM EMPLOYEE WHERE DNAME = :NEW.DNAME;
  IF v_count > 20 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Department capacity is full.');
  END IF;
END;
/

--WHEN TRYING TO CREATE A USERNAME FOR SAME EMPLOYEE OR A NON HR EMPLOYEE
CREATE OR REPLACE TRIGGER check_login
BEFORE INSERT ON LOGIN
FOR EACH ROW
BEGIN
    IF :NEW.EMP_ID IN (SELECT EMP_ID FROM LOGIN) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Employee already has a username.');
    ELSIF :NEW.EMP_ID NOT IN (SELECT EMP_ID FROM EMPLOYEE WHERE POSITION_TYPE = 'HR') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Employee is not a HR employee.');
    END IF;
END;
/

