--VIEWS
DROP VIEW EMPLOYEE_HIST;
DROP VIEW PROJECT_HIST;
DROP VIEW EMP_OT;
DROP VIEW VEHICLE_HIST;

--EMPLOYEE HISTORY
CREATE VIEW EMPLOYEE_HIST AS
SELECT ENAME, DNAME, HIREDATE AS
FROM EMPLOYEE;
SELECT * FROM EMPLOYEE_HIST;

--Vehicle History
CREATE VIEW VEHICLE_HIST AS
SELECT E.ENAME, V.V_MODEL, V.NEXT_M_DATE
FROM EMPLOYEE E, VEHICLE V
WHERE E.EMP_ID = V.EMP_ID;

SELECT * FROM VEHICLE_HIST;

--Project History
CREATE VIEW PROJECT_HIST AS
SELECT PNAME, DNAME
FROM PROJ;

SELECT * FROM PROJECT_HIST;

--Employee Overtime
CREATE VIEW EMP_OT AS
SELECT E.ENAME, O.OVERTIME_DATE, G.HOURLY_PAY, O.WORKING_HOURS, 
CASE 
    WHEN O.SHIFT = 'DAY' THEN  O.WORKING_HOURS * G.HOURLY_PAY 
    WHEN O.SHIFT = 'NIGHT' THEN 2*  O.WORKING_HOURS * G.HOURLY_PAY
    ELSE 0
END AS OVERTIME_EARNED
FROM OVERTIME O, EMPLOYEE E, GRADE G
WHERE O.EMP_ID = E.EMP_ID
AND E.SALARY BETWEEN G.MINSAL AND G.MAXSAL;

SELECT * FROM EMP_OT;